language: go
go:
  - 1.9
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
  - go get github.com/mitchellh/gox
  - go get github.com/google/go-cmp/cmp
  - go get github.com/yhat/scrape
  - go get golang.org/x/net/html
  - go get golang.org/x/net/html/atom
  - go get gopkg.in/gomail.v2
after_success:
  - gox -output "build/{{.OS}}_{{.Arch}}_{{.Dir}}"
